---
# Network Configuration
# Network Configuration
create_cloudbr0: true
configure_vlans: true
vlans:
  - id: 40
    name: vlan40-storage
    ip: "10.0.40.254/24"
  - id: 50
    name: vlan50-public
    ip: "10.0.50.254/24"
management_server_ip: "{{ groups['cloudstack_management'][0] }}"
utility_server_ip: "{{ groups['cloudstack_management'][0] }}"
gateway: "10.0.30.1"
dns1: "8.8.8.8"
dns2: "8.8.4.4"

# CloudStack paths
secondary_storage_path: "{{ ansible_user_dir }}/export/secondary"
primary_storage_path: "{{ ansible_user_dir }}/export/primary"

# NFS Server Toggle
enable_nfs_server: false
nfs_exports_file: "/etc/exports"
install_vagrant: false
github_runner_token: "ENTER_YOUR_TOKEN_HERE"

# Passwords
mysql_root_password: "password"
mysql_cloud_password: "password"
