---
# Produção — variáveis de ambiente

gateway: "151.246.233.1"
dns1: "8.8.8.8"
dns2: "8.8.4.4"

cloudstack_mgmt_host: "151.246.233.3"
cloudstack_mgmt_port: "30250"

# Prod: primary pool Gluster — instalar glusterfs-client nos 3 KVM hosts
install_glusterfs_client: true
cloudstack_bridge_type: openvswitch
cloudstack_private_bridge: cloudbr0
configure_network_bridge: false
